spring.application.name=Student-Management-API

spring.profiles.active=dev


# On desactive l'Open Session In View : chaque couche gere explicitement ses transactions.
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
